### ISSUE TITLE
exception - Class 'course_enrolment_manager' not found

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-auth_enrolkey#10]
From:

https://moodle.org/user/view.php?id=262358&course=1

> Hi
> after creating the user with the course code to enroll. notifies me the following error: "exception - Class 'course_enrolment_manager' not found" my moodle version 3.1.1. how can I solve that?
> 
> the user is registered and can log in, but does not validate the code enroll in the course and so I reapplies the key.

**Comment by brendanheywood** [comment]
I have no idea what this is so don't chase it too hard. I'm happy to close either way

**Comment by Peterburnett** [comment]
Yeah, without more information this is tough to diagnose
