### ISSUE TITLE
Text modification

### ISSUE THREAD

**Issue by martinsrepos** [catalyst/moodle-auth_enrolkey#106]
Hi, thank you for your great work on this plugin, I was wondering if you could add an option to modify the text of the signup instruction, or add support to more languages.

**Comment by brendanheywood** [comment]
hi @hotshataxd 

Editing the text is out of the box with this plugin and with all moodle plugins, see:

https://docs.moodle.org/401/en/Language_customisation

If you want to support other languages, the way moodle plugins work is that translations are all done centrally in a system called AMOS and anyone can sign up and contribute language packs for any plugin. You can do just individual strings so as little or as much as you want:

https://lang.moodle.org/
