### ISSUE TITLE
Instructions can't be customized. It shows the default

### ISSUE THREAD

**Issue by demontech** [catalyst/moodle-auth_enrolkey#13]
Hi,

Thank you for providing this plugin to the moodle community.

I'm trying to customized the login instructions with your plugin. It works fine if I use Email-based self-registration, but when I switched to Enrolment key based self-registration the login instructions are always the default. It doesn't matter if I change it on the instructions box.

![image](https://cloud.githubusercontent.com/assets/8148238/18563241/cb51260a-7b3b-11e6-9ca5-75695211385e.png)
![image](https://cloud.githubusercontent.com/assets/8148238/18563271/eb9918c8-7b3b-11e6-85f1-412682b0d7d3.png)
![image](https://cloud.githubusercontent.com/assets/8148238/18563335/253bd9ee-7b3c-11e6-9581-a5ab56348256.png)

I have purged all the catches and not success...

Thank you for your help

**Comment by brendanheywood** [comment]
Thanks, I've fixed this bug
