### ISSUE TITLE
Can not find data record in database table course.

### ISSUE THREAD

**Issue by genriq** [catalyst/moodle-auth_enrolkey#14]
After clicking on "Create my new account" on the Sign Up screen, when leaving Enrollment Key blank,  instead of getting the confirmation email, the following error is displayed: "Can not find data record in database table course." and the new user is logged in directly into Moodle. 

Thanks!

In debugging mode: 

Notice: Trying to get property of non-object in /var/www/ce_moodle/auth/enrolkey/view.php on line 43

Notice: Trying to get property of non-object in /var/www/ce_moodle/auth/enrolkey/view.php on line 45
Can not find data record in database table course.

More information about this error

×Debug info: SELECT id,category FROM {course} WHERE id IS NULL
[array (
)]
Error code: invalidrecord
×Stack trace:
line 1502 of /lib/dml/moodle_database.php: dml_missing_record_exception thrown
line 1478 of /lib/dml/moodle_database.php: call to moodle_database->get_record_select()
line 6952 of /lib/accesslib.php: call to moodle_database->get_record()
line 45 of /auth/enrolkey/view.php: call to context_course::instance()

**Comment by troyfmay** [comment]
This happened to our system when a user attempted to register with a group enrollment key. There is the aforementioned error screen, then it takes the student to the enrollment portal, where, if the same key attempted on registration is used, another error screen appears saying the user is not permitted to do this(Manage Groups) I believe the error is meaning. Then you hit Continue and are taken to your course!! You are not only enrolled in the course, but the group that was linked to the group key used.

**Comment by troyfmay** [comment]
OK. I have fixed some of it--made some progress. 

Now, the plugin will allow users to register and be enrolled into the course using a group enrollment key. However, it not only places them into the group you want them in, it places them into all the other groups associated with the course also!!!???

She's wild. But I'm taming her. Will keep you posted! :)

**Comment by Peterburnett** [comment]
Fixed in PR #28
