### ISSUE TITLE
Error code: coding error

### ISSUE THREAD

**Issue by Tejamvn** [catalyst/moodle-auth_enrolkey#18]
Hi,
There seems to be kind of functionality issues when trying to create a new account. When I click on "New account" or  "create new account" all I can see are some errors.

`Coding error detected, it must be fixed by a programmer: Can not render widget, renderer method (render_enrolkey_signup_form) not found.
Debug info: 
Error code: codingerror

Stack trace:
line 212 of /lib/outputrenderers.php: coding_exception thrown
line 108 of /login/signup.php: call to renderer_base->render()`

![enrolkey](https://user-images.githubusercontent.com/26163055/32774822-76a05d2c-c925-11e7-8e89-2a04928a9c91.png)

I think it may be the version that I am using, this error occurred on 3.3

**Comment by dheuring** [comment]
Tejamvn, this is the same issue reported in #15.  There was a hack-of-a-core-file solution that was suggested but it didn't work for me all that well as I explained in a recent post there.

**Comment by Peterburnett** [comment]
This issue with renderers not found should be fixed in PR #23
