### ISSUE TITLE
Blank screen after using no enrolment key

### ISSUE THREAD

**Issue by marcusboon** [catalyst/moodle-auth_enrolkey#2]
Originally submitted by Bert van der Hooft in https://moodle.org/plugins/auth_enrolkey

Using it on moodle 2.8.7.:

Leaving enrolment key open (not required): I end up in a blanc screen. On refreshment I see that I'm logged in. Account remains unconfirmed (that should be the case)

Using the enrolment key: I end up with a nice message that I'm enrolled in the course, but without role! So I do not see the learning activities (e.q. questionnaire).

I do like this plugin, but I uninstalled it, waiting for a slution for the abovemented two issues

**Comment by brendanheywood** [comment]
Fixed as part of #3
