### ISSUE TITLE
Is tokenvisible dead code?

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-auth_enrolkey#30]

**Comment by Peterburnett** [comment]
Tokenvisible is still used to decide whether or not to draw the enrolmentkey field in the signup form. It currently causes a few notices when it is not rendered, and that is not properly handled in the form validation, as well as during the signup process.
3 Options I can see,
1) I rip it out, and force token to always be rendered, but allow for empty
2) Allow token to be rendered as a hidden field if not visible, that will quiet the notices
3) leave as is, and put checks elsewhere to avoid notices

**Comment by brendanheywood** [comment]
If tokenvisible is false then signup_form should return null?

https://github.com/catalyst/moodle-auth_enrolkey/blob/master/auth.php#L266

**Comment by brendanheywood** [comment]
or rather call it parent

**Comment by Peterburnett** [comment]
Only problem is in user_signup it is assumed that the token is present https://github.com/catalyst/moodle-auth_enrolkey/blob/master/auth.php#L145
So I can just make it a blank hidden instead, and avoid notices for not set

**Comment by brendanheywood** [comment]
Should be the same login no? if it's false then that method should also exit early and just call it's parent?

Maybe this should extend the email signup auth class?

**Comment by brendanheywood** [comment]
Hang on even that doesn't make sense. If you don't want the token then this plugin is pointless. I don't get this setting at all. I'm leaning towards 1

**Comment by Peterburnett** [comment]
Ability to remove the token field implemented in PR #32
