### ISSUE TITLE
V3.8 - Sorry, the requested file could not be found

### ISSUE THREAD

**Issue by swinster** [catalyst/moodle-auth_enrolkey#35]
Hi,

I have just installed this in an attempt to make authentication an enrolment into and specifically a group within a course, but hit an issue. As soon as this is unhidden as an enrolment method, then "Self registration" is set to "Enrolment key based self-registration", when I then click the "New Account" link on the login page, I see:

```
Notice: Undefined property: stdClass::$loginhttps in /opt/bitnami/apps/moodle/htdocs/auth/enrolkey/enrolkey_signup_form.php on line 48

Notice: Undefined property: stdClass::$loginhttps in /opt/bitnami/apps/moodle/htdocs/auth/enrolkey/enrolkey_signup_form.php on line 62

Sorry, the requested file could not be found
More information about this error

Debug info: core/enrolkey_signup_form
Error code: filenotfound


Stack trace:

    line 123 of /lib/classes/output/mustache_template_finder.php: moodle_exception thrown
    line 54 of /lib/classes/output/mustache_filesystem_loader.php: call to core\output\mustache_template_finder::get_template_filepath()
    line 99 of /lib/mustache/src/Mustache/Loader/FilesystemLoader.php: call to core\output\mustache_filesystem_loader->getFileName()
    line 82 of /lib/mustache/src/Mustache/Loader/FilesystemLoader.php: call to Mustache_Loader_FilesystemLoader->loadFile()
    line 657 of /lib/mustache/src/Mustache/Engine.php: call to Mustache_Loader_FilesystemLoader->load()
    line 188 of /lib/outputrenderers.php: call to Mustache_Engine->loadTemplate()
    line 239 of /lib/outputrenderers.php: call to renderer_base->render_from_template()
    line 117 of /login/signup.php: call to renderer_base->render()
```

**Comment by brendanheywood** [comment]
@swinster all code mentioning loginhttps was removed a couple months ago. Are you on the latest version from this git repo?

**Comment by swinster** [comment]
@brendanheywood , hmm, I don;t think so. the Latest version on the Moodle plugin site is from 2016 - https://moodle.org/plugins/pluginversions.php?plugin=auth_enrolkey

**Comment by 2kv** [comment]
Hi,

What's the latest version?

I'm using  "Email-based self-registrationauth_email" ver. 2019052000
and hae the same bug.

Create new account button returns: 
"Sorry, the requested file could not be found"


How can we fix it?

**Comment by brendanheywood** [comment]
@swinster the latest versions of our plugins are always in github, the plugin directory is almost always out of date because it requires manual steps to publish. I know this is annoying. If you'd like to see this fixed please go and vote / comment for this moodle tracker so this can be automated:

https://tracker.moodle.org/browse/MDLSITE-4781

@2kv the plugin you mentioned, is not this plugin. I can't help with that.

@gleimermora will try to reproduce this, but I'm pretty sure this was already solved months ago and you just need to update to the latest version of the plugin.

**Comment by brendanheywood** [comment]
Confirmed this was fixed last october, so please update to the latest version:

https://github.com/catalyst/moodle-auth_enrolkey/commit/1a959778c1596ac9fe0a6e0dffa7f166f99864af#diff-b2d3108f6270aea76dd1df191bc80db5

**Comment by swinster** [comment]
@brendanheywood thanks. I really should learn to build these things from the GitHub source. Thanks for the pointers though. Whilst I work in this field (software manufacturing), I do not touch code, testing, or the build process. Something to learn when I have some time.

FWIW, 1 vote added to the auto build  process, plus one vote for the item that is blocking this as well.
