### ISSUE TITLE
suggestions for enrollment token option for existing users

### ISSUE THREAD

**Issue by jmayermsi** [catalyst/moodle-auth_enrolkey#40]
Wondering if there is a method to use enrollment token for existing users.  Once logged in as an existing user the individual would visit a page where they would enter an existing enrollment token which would enroll them in the right course.

**Comment by brendanheywood** [comment]
That already works out of the box, that is how enrollment key work in core without this plugin.

It is possible (but not implemented) to augment the login screen so you can login with an existing username, password, and optional enrolkey and get taken right in.

Lastly you can also install this companion block on say the dashboard so you can enrol from anywhere:

https://github.com/catalyst/moodle-block_enrolkey

**Comment by jmayermsi** [comment]
thanks for info
