### ISSUE TITLE
Group keys

### ISSUE THREAD

**Issue by Quxen** [catalyst/moodle-auth_enrolkey#5]
Hi 
Great plugin - but I have 1 issue.
It does not work with group enrolment keys.
Course enrollment keys works great.

I dont know if its an actual issue - but it  would be a nice feature :)

Thnx for the great work u've done with the plugin.

Kindly 
Quxen / Qurinius

**Comment by suankan** [comment]
Hi Quxen,

We fixed the Group enrolment keys functionality as of version 2016070600. Also added description to Readme.md on how to use Group enrolment keys.

Can you please test it independently and let us know if there are any issues.

**Comment by brendanheywood** [comment]
@Peterburnett I suspect this is good to go, I'd just like a unit test for it

**Comment by Peterburnett** [comment]
Unit tests have been added in PR #26
