### ISSUE TITLE
invalid key

### ISSUE THREAD

**Issue by hadadgar** [catalyst/moodle-auth_enrolkey#6]
Thanks for listening to the users.
I have tried to update the plugin, but when I want to log in as a user, I get this response:

The enrolment key you have entered is invalid

Do you have any idea how to solve it. I use Moodle 2.8.

Thanks
Arash

**Comment by hadadgar** [comment]
After 2 days it resolved. I don't know how.
Thanks.

**Comment by brendanheywood** [comment]
So is this open or closed?

**Comment by hadadgar** [comment]
This issue for me is closed. Sorry I am not familiar with these posts.

**Comment by brendanheywood** [comment]
No worries :)
