### ISSUE TITLE
Add ability to lock fields

### ISSUE THREAD

**Issue by nomisge** [catalyst/moodle-auth_enrolkey#60]
I would like to see the ability to lock fields from beeing edited, like I can do with manual or LDAP authentication.

Use Case: If you have both users who authenticate via LDAP, whose profile fields are partly filled with information by LDAP and users who use this plugin, you might want to lock the same fields (or a common set of fields).

Example: From LDAP you map the 'department' field with departments or grade-levels in your institution. Every member of your institution authenticates with LDAP. The field is locked.
To allow guests to register for special classes, you use this plugin. Those users dont need any value in the department field. But users can edit the field in their profile, although they should'nt. 

Problem: If the information in a profile field has functional use (e.g. to automatically be added into a cohort) their is actually a security issue. If its just for information, then filtering by those fields might show 'guest' users in e.g. a search result, if they edited their profile accordingly.

Workaround: Use custom-profile-fields, which duplicate the original profile field. Those can be hidden. That way the orignial fields are used to display the informaiton to the user, the custom-fields for functional use only. Downside: Users who authenticate with this plugin can still write something in the profile fields, although it has no meaning for them.

The code can propably be copied from the LDAP authentication plugin, or the manual authentication.

**Comment by brendanheywood** [comment]
Done :)
