### ISSUE TITLE
Reset Password

### ISSUE THREAD

**Issue by behoof** [catalyst/moodle-auth_enrolkey#7]
On moodle 3.1, the reset of passwords doesn't work with this magnificent authentication plugin. I also can't change the password of an user too.I need to change the authentication method for a certain user in order to change and reset passwords.

Can this be changed?

Bert

**Comment by brendanheywood** [comment]
Ah yes the auth type would be 'enrolkey' and not 'email'. We should make can_change_password() return true and other related methods, but probably an additional fix would be a new config item so you can specify which auth type the new users should be created as.

**Comment by behoof** [comment]
Hi Brendan,

Password is now changeable. Reset passwords by users doesn't work. They get an email with that message.

Bert

**Comment by brendanheywood** [comment]
Ok please pull and try again

**Comment by behoof** [comment]
Perfect!

**Comment by brendanheywood** [comment]
Ok great stuff, closing and I'll bump and release - thanks @behoof for your feedback and testing :)

**Comment by brendanheywood** [comment]
fyi Just realised email confirmation isn't implemented either, have logged it as #8

**Comment by CamBanfield** [comment]
Hi there,

We've encountered this problem and have updated to the latest plugin version which now allows text to be entered into the password box, however saving the change doesn't take affect so when attempting to login with the new password Moodle throws the standard "Invalid login, please try again" message. This is happening on Moodle 2.8.11

If you want any more information just let me know!

Thanks

**Comment by troyfmay** [comment]
I am having the same issue CamBanfield is experiencing. Is there any iterations available which still has the password reset functionality? If the password reset is not possible to fix, I believe it would be an amazing idea to have this instead then: _additional fix would be a new config item so you can specify which auth type the new users should be created as._
