### ISSUE TITLE
Enrol key security issue

### ISSUE THREAD

**Issue by parkeyparker** [catalyst/moodle-auth_enrolkey#81]
Redacted security issue, contents will return after a patch is released.

**Comment by catalystfd** [comment]
Thank you for the report, I'm following up internally to have people look at it.
We've temporarily redacted the issue as it is a security concern right now and will work on a patch for the issue.

**Comment by parkeyparker** [comment]
Thank you - I have updated the issue title as well to coincide with the redacting of the issue description

**Comment by Peterburnett** [comment]
Hi @parkeyparker Im digging into this now. I have verified the issue using some temp code, but I havent managed to actually replicate yet using code paths in the plugin. Can you please provide the moodle version, plugin commit target, and the database in use?
Thanks

**Comment by parkeyparker** [comment]
Hey @Peterburnett, we are actually a little behind on updates for Moodle so it may be a more recent Moodle update has resolved this (we are planning our upgrade at the moment). Versions as below:
Moodle: 3.5.15+ (Build: 20201121)
auth_enrolkey: 2020030300
MariaDB: 10.2.37

**Comment by brendanheywood** [comment]
hi @parkeyparker could you please send all future comms around this to Catalyst security AU <security@catalyst-au.net> instead of on this issue, thanks

**Comment by parkeyparker** [comment]
Closing this as was running an older version of auth_enrolkey (latest version on Moodle Plugin Directory is 2020011400). This issue has since been fixed.
