### ISSUE TITLE
There was an error enrolling in course

### ISSUE THREAD

**Issue by uugenio** [catalyst/moodle-auth_enrolkey#93]
Hi all,

After installing and setting up the plugin, everything seems to work ok BUT a message shows up just right up when the user finish the registration procedure: **There was an error enrolling in course. The error message is: enrolling inactive**

What could be happening? Thanks in advance.

Best regards

**Comment by brendanheywood** [comment]
It's hard to tell, the details are very light. A screen shot and ideally a stack trace with debugging turned fully up would help a lot

In any case I suspect it's a general enrollment setup problem and not specific to this plugin

**Comment by uugenio** [comment]
Thanks for your answer. I was able to solve the issue changing passwords for both, group and course enrol. :-)
